package dev.thuat.hotreload.gradle

import java.io.File
import org.gradle.api.GradleException
import org.junit.Rule
import org.junit.rules.TemporaryFolder
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

/** Content generation is pure (no I/O); [writeTo] does real (but network-free) file I/O. */
class HotReloadWrapperScriptTest {
    @get:Rule val tmp = TemporaryFolder()

    private val projectDir = File("/abs/project")

    @Test
    fun `content starts with the shebang on line 1, so the file is directly executable`() {
        val lines = HotReloadWrapperScript.content(projectDir, "com.example.app", "0.1.5").lines()
        assertEquals("#!/bin/sh", lines.first())
    }

    @Test
    fun `content carries the marker comment used by the clobber guard`() {
        val script = HotReloadWrapperScript.content(projectDir, "com.example.app", "0.1.5")
        assertTrue(script.contains(HotReloadWrapperScript.MARKER))
    }

    @Test
    fun `content names the plugin version it was generated for`() {
        val script = HotReloadWrapperScript.content(projectDir, "com.example.app", "0.1.5")
        assertTrue(script.contains("0.1.5"))
    }

    @Test
    fun `content execs the installed cli relative to the script's own location`() {
        val script = HotReloadWrapperScript.content(projectDir, "com.example.app", "0.1.5")
        assertTrue(script.contains("script_dir/build/hotreload/cli/bin/cli"))
        assertTrue(script.contains("dirname -- \"\$0\""))
    }

    @Test
    fun `content bakes in project and package before the passthrough args`() {
        val script = HotReloadWrapperScript.content(projectDir, "com.example.app", "0.1.5")
        val execLine = script.lines().single { it.trimStart().startsWith("exec ") }
        val project = execLine.indexOf("--project")
        val pkg = execLine.indexOf("--package")
        val passthrough = execLine.indexOf("\"\$@\"")
        assertTrue(
            project in 0 until pkg && pkg in 0 until passthrough,
            "expected --project, then --package, then \"\$@\" (last one wins), got: $execLine",
        )
        assertTrue(execLine.contains("--project \"/abs/project\""))
        assertTrue(execLine.contains("--package \"com.example.app\""))
    }

    @Test
    fun `blank application id falls back to a placeholder package`() {
        val script = HotReloadWrapperScript.content(projectDir, "", "0.1.5")
        assertTrue(script.contains("--package \"your.app.package\""))
    }

    @Test
    fun `passes all caller args through unconditionally`() {
        val script = HotReloadWrapperScript.content(projectDir, "com.example.app", "0.1.5")
        assertTrue(script.contains("\"\$@\""))
    }

    @Test
    fun `isOwnFile is true only for content carrying the marker`() {
        assertTrue(HotReloadWrapperScript.isOwnFile(HotReloadWrapperScript.content(projectDir, "p", "0.1.5")))
        assertEquals(false, HotReloadWrapperScript.isOwnFile("#!/bin/sh\necho hi\n"))
    }

    @Test
    fun `writeTo creates an executable file when none exists yet`() {
        val file = HotReloadWrapperScript.writeTo(tmp.root, "com.example.app", "0.1.5")
        assertEquals("hotreload", file.name)
        assertTrue(file.canExecute())
        assertTrue(file.readText().contains("com.example.app"))
    }

    @Test
    fun `writeTo overwrites a file it generated previously`() {
        HotReloadWrapperScript.writeTo(tmp.root, "com.example.app", "0.1.5")
        val second = HotReloadWrapperScript.writeTo(tmp.root, "com.example.app", "0.1.6")
        assertTrue(second.readText().contains("0.1.6"))
    }

    @Test
    fun `writeTo refuses to clobber a pre-existing file with no marker`() {
        File(tmp.root, "hotreload").writeText("#!/bin/sh\necho \"my own script, do not touch\"\n")
        val error = assertFailsWith<GradleException> {
            HotReloadWrapperScript.writeTo(tmp.root, "com.example.app", "0.1.5")
        }
        assertTrue(error.message!!.contains("wasn't generated by this task"))
        assertEquals(
            "echo \"my own script, do not touch\"",
            File(tmp.root, "hotreload").readLines()[1],
        ) // untouched
    }
}
