package dev.thuat.hotreload.gradle

import java.io.File
import java.util.jar.JarOutputStream
import java.util.zip.ZipEntry
import org.junit.Rule
import org.junit.rules.TemporaryFolder
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull

class RuntimeCoordinateDerivationTest {
    @get:Rule val tmp = TemporaryFolder()

    @Test
    fun `gradle module cache path resolves group and version`() {
        val path = "/Users/dev/.gradle/caches/modules-2/files-2.1/" +
            "com.github.nthuat.android-hot-reload/gradle-plugin/v0.1.0/" +
            "abc123deadbeef/gradle-plugin-v0.1.0.jar"
        val result = RuntimeCoordinateDerivation.parseGradleCachePath(path)
        assertEquals("com.github.nthuat.android-hot-reload" to "v0.1.0", result)
    }

    @Test
    fun `gradle module cache path without the files-2 1 marker is unrecognised`() {
        assertNull(RuntimeCoordinateDerivation.parseGradleCachePath("/some/random/path/plugin.jar"))
    }

    @Test
    fun `maven repository layout resolves group and version`() {
        val path = "/Users/dev/.m2/repository/dev/thuat/gradle-plugin/0.1.0-SNAPSHOT/" +
            "gradle-plugin-0.1.0-SNAPSHOT.jar"
        val result = RuntimeCoordinateDerivation.parseMavenLayoutPath(path, "gradle-plugin")
        assertEquals("dev.thuat" to "0.1.0-SNAPSHOT", result)
    }

    @Test
    fun `maven layout path without a m2-repository marker is unrecognised`() {
        assertNull(RuntimeCoordinateDerivation.parseMavenLayoutPath("/some/random/path/plugin.jar", "gradle-plugin"))
    }

    @Test
    fun `maven layout path where the artifact segment is right at the repository root is unrecognised`() {
        // No group directories between the repository root and the artifact — nothing to join into a group id.
        assertNull(
            RuntimeCoordinateDerivation.parseMavenLayoutPath(
                "/Users/dev/.m2/repository/gradle-plugin/0.1.0/x.jar",
                "gradle-plugin",
            )
        )
    }

    @Test
    fun `pom properties content resolves group and version`() {
        val content = """
            #Generated by Maven
            groupId=dev.thuat
            artifactId=gradle-plugin
            version=0.1.0-SNAPSHOT
        """.trimIndent()
        assertEquals("dev.thuat" to "0.1.0-SNAPSHOT", RuntimeCoordinateDerivation.parsePomProperties(content))
    }

    @Test
    fun `pom properties content missing a field is unrecognised`() {
        assertNull(RuntimeCoordinateDerivation.parsePomProperties("artifactId=gradle-plugin"))
    }

    @Test
    fun `deriving from a path that does not exist on disk returns null`() {
        val jarFile = File("/definitely/does/not/exist/gradle-plugin-1.0.jar")
        assertNull(RuntimeCoordinateDerivation.deriveFromJar(jarFile, "gradle-plugin"))
    }

    @Test
    fun `deriving from a real jar prefers embedded pom-properties over path parsing`() {
        // Deliberately named/placed so the path itself would parse to a different (wrong) group,
        // proving pom.properties wins when both are present.
        val jarFile = tmp.newFile("gradle-plugin-0.1.0-SNAPSHOT.jar")
        writeJarWithPomProperties(jarFile, groupId = "dev.thuat", version = "0.1.0-SNAPSHOT")
        val result = RuntimeCoordinateDerivation.deriveFromJar(jarFile, "gradle-plugin")
        assertEquals("dev.thuat" to "0.1.0-SNAPSHOT", result)
    }

    @Test
    fun `deriving from a real jar with no pom-properties falls back to maven layout path parsing`() {
        val repoRoot = tmp.newFolder(".m2", "repository")
        val jarDir = File(repoRoot, "dev/thuat/gradle-plugin/0.1.0-SNAPSHOT").apply { mkdirs() }
        val jarFile = File(jarDir, "gradle-plugin-0.1.0-SNAPSHOT.jar")
        writeEmptyJar(jarFile)
        val result = RuntimeCoordinateDerivation.deriveFromJar(jarFile, "gradle-plugin")
        assertEquals("dev.thuat" to "0.1.0-SNAPSHOT", result)
    }

    private fun writeEmptyJar(jarFile: File) {
        JarOutputStream(jarFile.outputStream()).use { it.putNextEntry(ZipEntry("META-INF/")); it.closeEntry() }
    }

    private fun writeJarWithPomProperties(jarFile: File, groupId: String, version: String) {
        JarOutputStream(jarFile.outputStream()).use { jar ->
            jar.putNextEntry(ZipEntry("META-INF/maven/$groupId/gradle-plugin/pom.properties"))
            jar.write("groupId=$groupId\nartifactId=gradle-plugin\nversion=$version\n".toByteArray())
            jar.closeEntry()
        }
    }
}
