package dev.thuat.hotreload.gradle

import java.io.File
import org.gradle.api.GradleException

/**
 * The `hotreload` wrapper script `hotReloadInstallCli` drops in the project root, plus the guard
 * that keeps re-runs from clobbering a file the task didn't create. Kept free of any network I/O
 * (unlike the rest of [InstallCliTask]) so both [content] and [writeTo] are unit-testable against
 * a plain temp directory.
 */
object HotReloadWrapperScript {
    const val FILE_NAME = "hotreload"

    /**
     * Unique line every generated script carries (line 2, right after the shebang — the shebang
     * itself must stay line 1 for `./hotreload` to be directly executable). [writeTo] looks for
     * this line to tell "ours, safe to regenerate" apart from "some unrelated file a user happens
     * to have at this path, do not touch it".
     */
    const val MARKER = "# Generated by hotReloadInstallCli -- DO NOT EDIT, this file is regenerated on every run."

    /**
     * [projectDir] and [applicationId] are baked in as literal `--project`/`--package` defaults so
     * day-to-day use is `./hotreload run` with no flags to remember. They're placed *before*
     * `"$@"` on the exec line: the CLI's arg parser (`Main.kt`) turns repeated `--flag value` pairs
     * into a map via `toMap()`, which keeps the LAST occurrence of a key, so anything the caller
     * passes on top (e.g. `./hotreload run --project /other/path`) wins over the baked-in default
     * instead of being shadowed by it.
     *
     * [sdkDir], when non-null (see [AndroidSdkResolution]), is baked in as an `ANDROID_HOME`
     * export instead of a CLI flag: the CLI (`Main.kt`'s `defaultAdb()`) only reads `ANDROID_HOME`
     * for the adb path when no `--adb` is passed, but exporting the env var also reaches the
     * nested Gradle Tooling API build `GradleCompiler` spawns to compile/dex the edited file,
     * which needs AGP to resolve the same SDK there — a plain `--adb` flag would cover only the
     * first of those. Uses `: "${'$'}{ANDROID_HOME:=...}"` (a POSIX no-op with a parameter-expansion
     * side effect) rather than an unconditional assignment, so a value the caller already exported
     * is never clobbered.
     *
     * [appModule], when non-null (see [HotReloadPlugin.findApplicationModulePaths] for how it's
     * resolved and the tie-break rule when a project has more than one `com.android.application`
     * module), is baked in as `--app-module` on the exec line, same rung as `--project`/
     * `--package` -- before `"$@"`, so an explicit `--app-module` the caller passes still wins.
     * Null (not just blank) means "couldn't resolve one" -- the flag is omitted entirely rather
     * than baking in an empty value, and the CLI's own `:app` default (`Main.kt`) applies exactly
     * as it did before this parameter existed.
     */
    fun content(
        projectDir: File,
        applicationId: String,
        pluginVersion: String,
        sdkDir: File? = null,
        appModule: String? = null,
    ): String {
        val pkg = applicationId.ifBlank { "your.app.package" }
        val sdkLines = if (sdkDir != null) {
            ": \"${'$'}{ANDROID_HOME:=${sdkDir.absolutePath}}\"\nexport ANDROID_HOME\n"
        } else {
            ""
        }
        val appModuleFlag = appModule?.takeIf { it.isNotBlank() }?.let { " --app-module \"$it\"" } ?: ""
        // A full standalone `|`-prefixed line (with its own trailing newline) rather than text
        // spliced mid-line, so trimMargin below still strips the margin off it like every other
        // line -- an empty string when there's no app module just collapses to no extra line.
        val appModuleNote = if (appModuleFlag.isNotEmpty()) {
            "            |# Application module: $appModule (override with --app-module <path>).\n"
        } else {
            ""
        }
        return """
            |#!/bin/sh
            |$MARKER
            |# Plugin version: $pluginVersion
            |#
            |# Thin wrapper around the CLI hotReloadInstallCli downloaded, with --project/--package
            |# (and, when this plugin could resolve one, --app-module and ANDROID_HOME) baked in so
            |# day-to-day use needs no flags and no environment to export:
            |#   ./hotreload run                       # watch mode
            |#   ./hotreload bootstrap                  # re-attach after the app restarts
            |#   ./hotreload cycle --file path/to/File.kt
            |# Flags you pass win over the baked-in --project/--package/--app-module (they come
            |# after on the command line, and the CLI keeps the last occurrence of a repeated
            |# flag), e.g.:
            |#   ./hotreload run --serial emulator-5554
${appModuleNote}            |# A baked-in ANDROID_HOME below is only set if not already exported, so a deliberate
            |# override in your shell always wins.
            |#
            |# This file has machine-specific absolute paths -- add it to .gitignore.
            |set -e
            |script_dir=${'$'}(CDPATH= cd -- "${'$'}(dirname -- "${'$'}0")" && pwd)
            |${sdkLines}cmd="${'$'}1"
            |if [ "${'$'}#" -gt 0 ]; then shift; fi
            |exec "${'$'}script_dir/build/hotreload/cli/bin/cli" "${'$'}cmd" --project "${projectDir.absolutePath}" --package "$pkg"$appModuleFlag "${'$'}@"
            |
        """.trimMargin()
    }

    /** True if [existingContent] is a script this task generated (vs. an unrelated user file). */
    fun isOwnFile(existingContent: String): Boolean = existingContent.contains(MARKER)

    /**
     * Writes the wrapper into [projectDir], refusing to overwrite a pre-existing file that isn't
     * one of ours. Sets the executable bit like [InstallCliTask.install] does for `bin/cli`.
     */
    fun writeTo(
        projectDir: File,
        applicationId: String,
        pluginVersion: String,
        sdkDir: File? = null,
        appModule: String? = null,
    ): File {
        val file = File(projectDir, FILE_NAME)
        if (file.isFile && !isOwnFile(file.readText())) {
            throw GradleException(
                "hotReloadInstallCli: $file already exists and wasn't generated by this task (no " +
                    "marker comment found) -- refusing to overwrite it. Remove or rename it, then " +
                    "re-run hotReloadInstallCli.",
            )
        }
        file.writeText(content(projectDir, applicationId, pluginVersion, sdkDir, appModule))
        file.setExecutable(true, false)
        return file
    }
}
