package dev.thuat.hotreload.gradle

import java.io.File
import org.gradle.api.GradleException

/**
 * The `hotreload` wrapper script `hotReloadInstallCli` drops in the project root, plus the guard
 * that keeps re-runs from clobbering a file the task didn't create. Kept free of any network I/O
 * (unlike the rest of [InstallCliTask]) so both [content] and [writeTo] are unit-testable against
 * a plain temp directory.
 */
object HotReloadWrapperScript {
    const val FILE_NAME = "hotreload"

    /**
     * Unique line every generated script carries (line 2, right after the shebang — the shebang
     * itself must stay line 1 for `./hotreload` to be directly executable). [writeTo] looks for
     * this line to tell "ours, safe to regenerate" apart from "some unrelated file a user happens
     * to have at this path, do not touch it".
     */
    const val MARKER = "# Generated by hotReloadInstallCli -- DO NOT EDIT, this file is regenerated on every run."

    /**
     * [projectDir] and [applicationId] are baked in as literal `--project`/`--package` defaults so
     * day-to-day use is `./hotreload run` with no flags to remember. They're placed *before*
     * `"$@"` on the exec line: the CLI's arg parser (`Main.kt`) turns repeated `--flag value` pairs
     * into a map via `toMap()`, which keeps the LAST occurrence of a key, so anything the caller
     * passes on top (e.g. `./hotreload run --project /other/path`) wins over the baked-in default
     * instead of being shadowed by it.
     */
    fun content(projectDir: File, applicationId: String, pluginVersion: String): String {
        val pkg = applicationId.ifBlank { "your.app.package" }
        return """
            |#!/bin/sh
            |$MARKER
            |# Plugin version: $pluginVersion
            |#
            |# Thin wrapper around the CLI hotReloadInstallCli downloaded, with --project/--package
            |# baked in so day-to-day use needs no flags:
            |#   ./hotreload run                       # watch mode
            |#   ./hotreload bootstrap                  # re-attach after the app restarts
            |#   ./hotreload cycle --file path/to/File.kt
            |# Flags you pass win over the baked-in --project/--package (they come after on the
            |# command line, and the CLI keeps the last occurrence of a repeated flag), e.g.:
            |#   ./hotreload run --serial emulator-5554
            |#
            |# This file has machine-specific absolute paths -- add it to .gitignore.
            |set -e
            |script_dir=${'$'}(CDPATH= cd -- "${'$'}(dirname -- "${'$'}0")" && pwd)
            |cmd="${'$'}1"
            |if [ "${'$'}#" -gt 0 ]; then shift; fi
            |exec "${'$'}script_dir/build/hotreload/cli/bin/cli" "${'$'}cmd" --project "${projectDir.absolutePath}" --package "$pkg" "${'$'}@"
            |
        """.trimMargin()
    }

    /** True if [existingContent] is a script this task generated (vs. an unrelated user file). */
    fun isOwnFile(existingContent: String): Boolean = existingContent.contains(MARKER)

    /**
     * Writes the wrapper into [projectDir], refusing to overwrite a pre-existing file that isn't
     * one of ours. Sets the executable bit like [InstallCliTask.install] does for `bin/cli`.
     */
    fun writeTo(projectDir: File, applicationId: String, pluginVersion: String): File {
        val file = File(projectDir, FILE_NAME)
        if (file.isFile && !isOwnFile(file.readText())) {
            throw GradleException(
                "hotReloadInstallCli: $file already exists and wasn't generated by this task (no " +
                    "marker comment found) -- refusing to overwrite it. Remove or rename it, then " +
                    "re-run hotReloadInstallCli.",
            )
        }
        file.writeText(content(projectDir, applicationId, pluginVersion))
        file.setExecutable(true, false)
        return file
    }
}
