package dev.thuat.hotreload.cli

import java.nio.file.FileSystems
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths
import java.nio.file.StandardWatchEventKinds
import kotlin.io.path.relativeTo
import kotlin.system.exitProcess

fun main(args: Array<String>) {
    if (args.isEmpty()) usage()
    val cmd = args[0]
    val opts = args.drop(1).chunked(2).mapNotNull { pair ->
        if (pair.size == 2 && pair[0].startsWith("--")) pair[0].removePrefix("--") to pair[1] else null
    }.toMap()

    val projectDir = Paths.get(opts["project"] ?: fail("--project required")).toAbsolutePath().normalize()
    val pkg = opts["package"] ?: fail("--package required")
    val config = ReloadConfig(
        projectDir = projectDir,
        pkg = pkg,
        serial = opts["serial"],
        adbPath = opts["adb"] ?: defaultAdb(),
        agentSoDir = resolveAgentSoDir(
            explicit = opts["agent-so-dir"],
            homeEnv = System.getenv("HOTRELOAD_HOME"),
            cwd = Paths.get("").toAbsolutePath(),
        ),
        appModule = opts["app-module"] ?: ":app",
        localPort = opts["port"]?.let { it.toIntOrNull() ?: fail("--port must be an integer, got '$it'") } ?: derivePort(pkg),
        javaHome = opts["java-home"]?.let { Paths.get(it) },
    )

    // Before any device or compile work (bootstrap/cycle/run all reach here first): the Tooling
    // API uses the CLI's own JVM (or --java-home) for the consumer project's build daemon by
    // default, and a JDK too new for that project's Gradle version is the single most likely
    // first-run failure — most default JDKs are 22+ now. See JdkPreflight.kt for the version-
    // ceiling logic and where each number comes from.
    jdkPreflightCheck(projectDir, config.javaHome)?.let { exitWith(it) }

    val orchestrator = ReloadOrchestrator(config)

    when (cmd) {
        "bootstrap" -> exitWith(orchestrator.bootstrap())
        "cycle" -> {
            val file = Paths.get(opts["file"] ?: fail("--file required"))
            exitWith(orchestrator.cycle(file))
        }
        "run" -> {
            val boot = orchestrator.bootstrap()
            if (boot !is CycleOutcome.Reloaded) exitWith(boot)
            println("hotreload ready — watching ${config.projectDir}")
            watchLoop(config.projectDir, orchestrator)
        }
        else -> usage()
    }
}

// The CLI's own start script (bin/cli, generated by the `application` plugin, see
// cli/build.gradle.kts's startScripts doLast) exports HOTRELOAD_HOME=$APP_HOME so a bundled
// agent (see the same file's distributions block, which copies
// agent/build/.../mergeDebugNativeLibs/out/lib into "<APP_HOME>/agent") can be found with zero
// configuration when the CLI is run from an installDist/distZip build — the documented, intended
// workflow (README quickstart: run from the CONSUMER project dir, not the tool checkout). Absent
// when launched another way (e.g. `gradle run` from a dev checkout of this repo), in which case
// we fall back to the old CWD-relative path used for local iteration on the tool itself.
// `explicit` (--agent-so-dir) always wins over both. Pure so it's unit testable without a real
// install.
internal fun resolveAgentSoDir(explicit: String?, homeEnv: String?, cwd: Path): Path = when {
    explicit != null -> Paths.get(explicit)
    homeEnv != null -> Paths.get(homeEnv).resolve("agent")
    else -> cwd.resolve("agent/build/intermediates/merged_native_libs/debug/mergeDebugNativeLibs/out/lib")
}

// Segment-based, not substring: the old `path.contains("src") && !path.contains("build")` check
// matched anywhere in the *absolute* path. A project checked out under a path containing "build"
// (e.g. ~/repos/build-tools/myapp) registered zero watchers — `run` then hangs forever with no
// indication why — and a path containing "src" (e.g. ~/src/myapp) happily registered .git/.idea
// as "src" dirs too. Pure so it's directly unit testable without a real filesystem/WatchService.
internal fun isWatchableDir(dir: Path, projectDir: Path): Boolean {
    if (dir == projectDir) return false
    val segments = dir.relativeTo(projectDir).map { it.toString() }
    return segments.none { it.startsWith(".") } &&   // skip .git, .gradle, .idea, .hotreload, ...
        segments.none { it == "build" } &&
        segments.any { it == "src" }
}

private fun watchLoop(projectDir: Path, orchestrator: ReloadOrchestrator): Nothing {
    val watcher = FileSystems.getDefault().newWatchService()
    Files.walk(projectDir).use { stream ->
        stream.filter { Files.isDirectory(it) && isWatchableDir(it, projectDir) }
            .forEach { it.register(watcher, StandardWatchEventKinds.ENTRY_MODIFY, StandardWatchEventKinds.ENTRY_CREATE) }
    }
    while (true) {
        val key = watcher.take()
        val dir = key.watchable() as Path
        val changedKt = key.pollEvents().mapNotNull { (it.context() as? Path)?.let(dir::resolve) }
            .filter { it.toString().endsWith(".kt") }
        key.reset()
        if (changedKt.isEmpty()) continue
        Thread.sleep(100)  // debounce editor write bursts
        report(orchestrator.cycle(changedKt.first()))
    }
}

// Short state-guarantee text per tier, for the CLI's post-reload line — see
// ComposeInvalidator.reload's three-tier fallback chain and the README's "Reload tiers" table.
private val tierGuarantee = mapOf(
    "tier1" to "remember state preserved",
    "tier2" to "UI state reset",
    "tier3" to "activity recreated",
    "tier-timeout" to "reload confirmation timed out",
)

// Caps the skipped-classes line at a handful of names so it stays one short line even when a
// file has many @Preview-only lambda holders — see summarizeSkipped's caller.
private const val MAX_SKIPPED_NAMES_SHOWN = 3

private fun summarizeSkipped(skipped: List<String>): String {
    val shown = skipped.take(MAX_SKIPPED_NAMES_SHOWN).joinToString()
    val extra = skipped.size - MAX_SKIPPED_NAMES_SHOWN
    return if (extra > 0) "$shown, +$extra more" else shown
}

// Compact per-phase breakdown appended to the reload line — always on rather than behind a
// flag, so a slow cycle is diagnosable without having to know to ask for it (see F1: a 24s
// cycle looked like one opaque number until this was measured phase-by-phase). Empty for
// bootstrap's synthetic Reloaded(0ms, phaseMillis = emptyMap()) result, which prints nothing.
private fun formatPhaseTimings(phaseMillis: Map<String, Long>): String {
    if (phaseMillis.isEmpty()) return ""
    val parts = phaseMillis.entries.joinToString(" · ") { (phase, ms) -> "$phase %.1fs".format(ms / 1000.0) }
    return " ($parts)"
}

private fun report(outcome: CycleOutcome) {
    when (outcome) {
        is CycleOutcome.Reloaded -> {
            // Non-fatal heads-up (currently: on-device runtime version unknown — see
            // ReloadOrchestrator.checkRuntimeVersion) printed ahead of the normal reload/
            // bootstrap line, never in place of it — the outcome that carries it already
            // succeeded.
            outcome.warning?.let { println("⚠ $it") }
            if (outcome.classes.isEmpty() && outcome.skipped.isNotEmpty()) {
                // Every changed class in this cycle was skipped as not-currently-loaded (e.g. a
                // file that only touches @Preview-only lambda holders) — nothing was redefined,
                // so this is a distinct outcome from a normal reload, not a 0-class "success".
                println(
                    "· nothing applied — ${outcome.skipped.size} changed class(es) not currently loaded: " +
                        "${summarizeSkipped(outcome.skipped)} (still running the installed APK's version " +
                        "until the next full rebuild)"
                )
            } else {
                val tierSuffix = outcome.tier?.let { " [$it — ${tierGuarantee[it] ?: "unknown"}]" } ?: ""
                println(
                    "✓ reloaded ${outcome.classes.size} class(es) in ${outcome.millis}ms$tierSuffix: " +
                        "${outcome.classes.joinToString()}${formatPhaseTimings(outcome.phaseMillis)}"
                )
                if (outcome.skipped.isNotEmpty()) {
                    println(
                        "  ⚠ skipped ${outcome.skipped.size} not-yet-loaded class(es), using the installed APK's " +
                            "version until the next full rebuild: ${summarizeSkipped(outcome.skipped)}"
                    )
                }
            }
        }
        is CycleOutcome.NoChanges -> println("· no bytecode changes")
        is CycleOutcome.CompileError -> println("✗ compile error:\n${outcome.output}")
        is CycleOutcome.Incompatible -> println("✗ incompatible change: ${outcome.reason}\n  → run a full rebuild + reinstall, then 'hotreload bootstrap' again")
        is CycleOutcome.DeviceError -> println("✗ device/agent: ${outcome.reason}")
        is CycleOutcome.EnvironmentError -> println("✗ environment: ${outcome.reason}")
    }
}

private fun exitWith(outcome: CycleOutcome): Nothing {
    report(outcome)
    exitProcess(
        when (outcome) {
            is CycleOutcome.Reloaded, CycleOutcome.NoChanges -> 0
            is CycleOutcome.CompileError -> 1
            is CycleOutcome.Incompatible -> 2
            is CycleOutcome.DeviceError, is CycleOutcome.EnvironmentError -> 3
        }
    )
}

private fun defaultAdb(): String {
    val home = System.getenv("ANDROID_HOME") ?: System.getenv("ANDROID_SDK_ROOT")
        ?: fail("set ANDROID_HOME or pass --adb")
    return "$home/platform-tools/adb"
}

private fun usage(): Nothing {
    println(
        "usage: hotreload <bootstrap|cycle|run> --project <dir> --package <pkg> [--serial S] " +
            "[--file f.kt] [--adb path] [--agent-so-dir dir] [--app-module :app] " +
            "[--port N (default: derived per-package, see ReloadOrchestrator.derivePort)] " +
            "[--java-home <path> (run the build daemon on a specific JDK instead of this CLI's own)]"
    )
    exitProcess(64)
}

private fun fail(msg: String): Nothing {
    System.err.println("error: $msg")
    exitProcess(64)
}
